# coding: utf-8

"""
    Pulse API

    Integrate all of your testing apps with Pulse API

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.user_date_schema import UserDateSchema


class TestUserDateSchema(unittest.TestCase):
    """ UserDateSchema unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserDateSchema(self):
        """
        Test UserDateSchema
        """
        model = swagger_client.models.user_date_schema.UserDateSchema()


if __name__ == '__main__':
    unittest.main()
