# coding: utf-8

"""
    Pulse API

    Integrate all of your testing apps with Pulse API

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.work_items_api import WorkItemsApi


class TestWorkItemsApi(unittest.TestCase):
    """ WorkItemsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.work_items_api.WorkItemsApi()

    def tearDown(self):
        pass

    def test_create_work_item(self):
        """
        Test case for create_work_item

        createWorkItem
        """
        pass

    def test_delete_work_item(self):
        """
        Test case for delete_work_item

        deleteWorkItem
        """
        pass

    def test_get_all_work_items(self):
        """
        Test case for get_all_work_items

        getWorkItems
        """
        pass

    def test_get_work_item(self):
        """
        Test case for get_work_item

        getWorkItem
        """
        pass

    def test_update_work_item(self):
        """
        Test case for update_work_item

        updateWorkItem
        """
        pass


if __name__ == '__main__':
    unittest.main()
