# coding: utf-8

"""
    Pulse API

    Integrate all of your testing apps with Pulse API

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.login_logout_api import LoginLogoutApi


class TestLoginLogoutApi(unittest.TestCase):
    """ LoginLogoutApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.login_logout_api.LoginLogoutApi()

    def tearDown(self):
        pass

    def test_login(self):
        """
        Test case for login

        login
        """
        pass

    def test_logout(self):
        """
        Test case for logout

        logout
        """
        pass


if __name__ == '__main__':
    unittest.main()
