# coding: utf-8

"""
    Pulse API

    Integrate all of your testing apps with Pulse API

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.components_api import ComponentsApi


class TestComponentsApi(unittest.TestCase):
    """ ComponentsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.components_api.ComponentsApi()

    def tearDown(self):
        pass

    def test_create_component(self):
        """
        Test case for create_component

        createComponent
        """
        pass

    def test_delete_component(self):
        """
        Test case for delete_component

        deleteComponent
        """
        pass

    def test_get_all_components(self):
        """
        Test case for get_all_components

        getComponents
        """
        pass

    def test_get_component(self):
        """
        Test case for get_component

        getComponent
        """
        pass

    def test_update_component(self):
        """
        Test case for update_component

        updateComponent
        """
        pass


if __name__ == '__main__':
    unittest.main()
