# coding: utf-8

"""
    Pulse API

    Integrate all of your testing apps with Pulse API

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ ProjectsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.projects_api.ProjectsApi()

    def tearDown(self):
        pass

    def test_create_project(self):
        """
        Test case for create_project

        createProject
        """
        pass

    def test_get_all_projects(self):
        """
        Test case for get_all_projects

        getProjects
        """
        pass

    def test_get_project(self):
        """
        Test case for get_project

        getProject
        """
        pass

    def test_update_project(self):
        """
        Test case for update_project

        updateProject
        """
        pass


if __name__ == '__main__':
    unittest.main()
