# coding: utf-8

"""
    Pulse API

    Integrate all of your testing apps with Pulse API

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.organizations_api import OrganizationsApi


class TestOrganizationsApi(unittest.TestCase):
    """ OrganizationsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.organizations_api.OrganizationsApi()

    def tearDown(self):
        pass

    def test_get_all_organizations(self):
        """
        Test case for get_all_organizations

        getOrganizations
        """
        pass

    def test_get_organization(self):
        """
        Test case for get_organization

        getOrganization
        """
        pass


if __name__ == '__main__':
    unittest.main()
