# coding: utf-8

"""
    Pulse API

    Integrate all of your testing apps with Pulse API

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.projects import Projects


class TestProjects(unittest.TestCase):
    """ Projects unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjects(self):
        """
        Test Projects
        """
        model = swagger_client.models.projects.Projects()


if __name__ == '__main__':
    unittest.main()
