# coding: utf-8

"""
    Pulse API

    Integrate all of your testing apps with Pulse API

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.sprints_api import SprintsApi


class TestSprintsApi(unittest.TestCase):
    """ SprintsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.sprints_api.SprintsApi()

    def tearDown(self):
        pass

    def test_create_sprint(self):
        """
        Test case for create_sprint

        createSprint
        """
        pass

    def test_delete_sprint(self):
        """
        Test case for delete_sprint

        deleteSprint
        """
        pass

    def test_get_all_sprints(self):
        """
        Test case for get_all_sprints

        getSprints
        """
        pass

    def test_get_sprint(self):
        """
        Test case for get_sprint

        getSprint
        """
        pass

    def test_update_sprint(self):
        """
        Test case for update_sprint

        updateSprint
        """
        pass


if __name__ == '__main__':
    unittest.main()
