# coding: utf-8

"""
    Pulse API

    Integrate all of your testing apps with Pulse API

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.releases_api import ReleasesApi


class TestReleasesApi(unittest.TestCase):
    """ ReleasesApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.releases_api.ReleasesApi()

    def tearDown(self):
        pass

    def test_create_release(self):
        """
        Test case for create_release

        createRelease
        """
        pass

    def test_delete_release(self):
        """
        Test case for delete_release

        deleteRelease
        """
        pass

    def test_get_all_releases(self):
        """
        Test case for get_all_releases

        getReleases
        """
        pass

    def test_get_release(self):
        """
        Test case for get_release

        getRelease
        """
        pass

    def test_update_release(self):
        """
        Test case for update_release

        updateRelease
        """
        pass


if __name__ == '__main__':
    unittest.main()
