# coding: utf-8

"""
    Pulse API

    Integrate all of your testing apps with Pulse API

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class LinkedTestCaseSchema(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, test_case_id=None, execution=None):
        """
        LinkedTestCaseSchema - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'test_case_id': 'str',
            'execution': 'object'
        }

        self.attribute_map = {
            'test_case_id': 'testCaseId',
            'execution': 'execution'
        }

        self._test_case_id = test_case_id
        self._execution = execution

    @property
    def test_case_id(self):
        """
        Gets the test_case_id of this LinkedTestCaseSchema.
        testCaseId of the LinkedTestCaseSchema.

        :return: The test_case_id of this LinkedTestCaseSchema.
        :rtype: str
        """
        return self._test_case_id

    @test_case_id.setter
    def test_case_id(self, test_case_id):
        """
        Sets the test_case_id of this LinkedTestCaseSchema.
        testCaseId of the LinkedTestCaseSchema.

        :param test_case_id: The test_case_id of this LinkedTestCaseSchema.
        :type: str
        """
        if test_case_id is None:
            raise ValueError("Invalid value for `test_case_id`, must not be `None`")

        self._test_case_id = test_case_id

    @property
    def execution(self):
        """
        Gets the execution of this LinkedTestCaseSchema.
        execution of the LinkedTestCaseSchema.

        :return: The execution of this LinkedTestCaseSchema.
        :rtype: object
        """
        return self._execution

    @execution.setter
    def execution(self, execution):
        """
        Sets the execution of this LinkedTestCaseSchema.
        execution of the LinkedTestCaseSchema.

        :param execution: The execution of this LinkedTestCaseSchema.
        :type: object
        """

        self._execution = execution

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
